spring:
  application:
    name: blue-cat
  datasource:
    url: jdbc:mysql://x.x.x.x:3306/blue_cat?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: xxxx
    password: xxxx
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never   # always, never
    schema:
      - classpath:sql/schema.sql
    data:
      - classpath:sql/data.sql
    sql-script-encoding: UTF-8
mybatis:
  mapperLocations: classpath:/mybatis/mapper/**/*.xml
  configLocation: classpath:/mybatis/config/mybatis-config.xml
logging:
  config: classpath:logback-spring.xml

